const contacts = [
  {
    firstName: "Christian",
    status: "available",
    email: "christian@yahoo.com",
    phone: "323-555-1234",
    address: "6539 Wilton Ave.",
    city: "Culver City",
    state: "CA",
    zip: 90234,
  },
  {
    firstName: "Rich",
    status: "available",
    email: "rich@tripod.com",
    phone: "323-555-1234",
    address: "6539 Wilton Ave.",
    city: "Culver City",
    state: "CA",
    zip: 90234,
  },
  {
    firstName: "Scott",
    status: "available",
    email: "scott@mailinator.com",
    phone: "323-555-1234",
    address: "6539 Wilton Ave.",
    city: "Culver City",
    state: "CA",
    zip: 90234,
  },
  {
    firstName: "Danny",
    status: "available",
    email: "danny@hotmail.com",
    phone: "323-555-1234",
    address: "6539 Wilton Ave.",
    city: "Culver City",
    state: "CA",
    zip: 90234,
  },
  {
    firstName: "Taka",
    status: "away",
    email: "taka@myspace.com",
    phone: "323-555-1234",
    address: "6539 Wilton Ave.",
    city: "Culver City",
    state: "CA",
    zip: 90234,
  },
  {
    firstName: "Tim",
    status: "idle",
    email: "tim@netscape.com",
    phone: "323-555-1234",
    address: "6539 Wilton Ave.",
    city: "Culver City",
    state: "CA",
    zip: 90234,
  },
  {
    firstName: "Patrick",
    status: "available",
    email: "patrick@live.com",
    phone: "323-555-1234",
    address: "6539 Wilton Ave.",
    city: "Culver City",
    state: "CA",
    zip: 90234,
  },
  {
    firstName: "Jacques",
    status: "idle",
    email: "jacques@aol.com",
    phone: "323-555-1234",
    address: "6539 Wilton Ave.",
    city: "Culver City",
    state: "CA",
    zip: 90234,
  },
]
export default contacts
